<?php
$class=$gb_url4;
//主页
//index
if($class=="index")
{
    require("./website/".$tid."/admin/main_index.php");
}
//无赋值
elseif($class=="error")
{
    require("./website/".$tid."/admin/main_index.php");
}
//刷新数据_网页全部
elseif($class=="refreshAll")
{
    require("./website/".$tid."/admin/plugin/refresh/all_html.php");
}
?>